### PR TITLE
Updated documentation to run installer for Python 3

### PR DESCRIPTION
**Pull request by red2k18**

### CODE REVIEW

**Comment by red2k18** [comment]
Fixed #2890

**Comment by dekuhn** [comment]
Adding comment to force update

**Comment by dekuhn** [comment]
Adding comment after change of mail address on profile

**Comment by red2k18** [comment]
Adding comment for git to pick up changes.

**Comment by red2k18** [comment]
Opened #2894 after fixing CLA issues.

**Pull request closed without merging**
