### PR TITLE
Servicemanagement client getConfig()

### PR DESCRIPTION
**Pull request by bobklein2**
Thanks for opening a Pull Request!

Here's a handy checklist to ensure your PR goes smoothly.

- [ X ] I signed Google's [Contributor License Agreement](https://opensource.google.com/docs/cla/)
- [ X ] My code conforms to Google's [python style](https://google.github.io/styleguide/pyguide.html).
- [ X ] My PR at a minimum doesn't decrease unit-test coverage (if applicable).
- [ X ] My PR has been functionally tested.
- [ X ] All of the [unit-tests](https://forsetisecurity.org/docs/latest/develop/dev/testing.html) still pass.
- [ X ] Running `pylint --rcfile=pylintrc` passes.

These guidelines and more can be found in our [contributing guidelines](https://github.com/GoogleCloudPlatform/forseti-security/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dekuhn** [comment]
FYI: We have announced a code freeze starting May 16, 2019, and ending May 30, 2019. During this time we won't be merging any new pull requests. For more details you can read the full announcement details [here](https://groups.google.com/a/forsetisecurity.org/forum/#!topic/announce/iIV-sr5zfds).

**Comment by dekuhn** [comment]
@ahoying @bobklein2 What is required to get this PR over the finish line?

**Comment by kevensen** [comment]
@ahoying @bobklein2 Is this PR still a work in progress?  If so, please update the branch and comment here.  We'll make sure it's appropriately tracked in our backlog.

**Comment by blueandgold** [comment]
@bobklein2 @kevensen @ahoying Also the API client is updated, I don't see how it's being used (e.g. for inventory)

**Comment by gkowalski-google** [comment]
@bobklein2 Is this something that you would still like to contribute? Can you provide any context as to exactly what this change is for? Please let me know if I can help to get this PR merged in if still needed.

**Pull request merged**
