### PR TITLE
Use private IP address with Cloud SQL Proxy

### LINKED ISSUE #2714: Research on: cloud_sql_proxy should use private IP's
cloud_sql_proxy should use private IP's to connect to Cloud SQL. This is a more secure way and more compliant way of connecting to database.

### PR DESCRIPTION
**Pull request by aaron-lane**
Fixes #2715
Fixes #2714

Thanks for opening a Pull Request!

Here's a handy checklist to ensure your PR goes smoothly.

- [x] I signed Google's [Contributor License Agreement](https://opensource.google.com/docs/cla/)
- [x] My code conforms to Google's [python style](https://google.github.io/styleguide/pyguide.html).
- [x] My PR at a minimum doesn't decrease unit-test coverage (if applicable).
- [ ] My PR has been functionally tested.
- [ ] All of the [tests](https://forsetisecurity.org/docs/latest/develop/dev/testing.html) pass

These guidelines and more can be found in our [contributing guidelines](https://github.com/forseti-security/forseti-security/blob/dev/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dekuhn** [comment]
FYI: We have announced a code freeze starting May 16, 2019, and ending May 30, 2019. During this time we won't be merging any new pull requests. For more details you can read the full announcement details [here](https://groups.google.com/a/forsetisecurity.org/forum/#!topic/announce/iIV-sr5zfds).

**Comment by hshin-g** [comment]
@aaron-lane It looks like there are branch conflicts that need to be resolved before approving- would you be able them?

**Comment by aaron-lane** [comment]
@hshin-g done! I noticed `cloudsqlproxy.template.yaml` was removed by #2885. Is this change still relevant?

**Comment by hshin-g** [comment]
Closing as per comment in PR #2715.

**Pull request closed without merging**
