### PR TITLE
Add --version flag to Forseti CLI

### PR DESCRIPTION
**Pull request by garrettwong**
Thanks for opening a Pull Request!

Here's a handy checklist to ensure your PR goes smoothly.

- [x] I signed Google's [Contributor License Agreement](https://opensource.google.com/docs/cla/)
- [x] My code conforms to Google's [python style](https://google.github.io/styleguide/pyguide.html).
- [x] My PR at a minimum doesn't decrease unit-test coverage (if applicable).
- [x]v My PR has been functionally tested.
- [x] All of the [tests](https://forsetisecurity.org/docs/latest/develop/dev/testing.html) pass.
- [x] I have submitted a corresponding PR for documentation in the `forsetisecurity.org-dev branch` and included this on this PR (if applicable).
- [x] My documentation has been functionally tested and used (if applicable).
- [x] I have submitted a corresponding PR in the [Forseti Terraform module](https://github.com/forseti-security/terraform-google-forseti) (if applicable).

These guidelines and more can be found in our [contributing guidelines](https://github.com/forseti-security/forseti-security/blob/dev/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by gkowalski-google** [comment]
Hi @garrettwong, thanks for the PR! Can you review the lint errors? Looks like all tests have passed.

```
W:899, 0: "_, client, config, output" differing in parameter documentation (differing-param-doc)
W:899, 0: "_, client, config, output" differing in parameter type documentation (differing-type-doc)
```

**Comment by blueandgold** [comment]
Hi @garrettwong are you able to address the lint comments, that in the build failure?

**Comment by blueandgold** [comment]
@garrettwong are you able to fix the lint error above?  We have a release coming soon, so hope this can go in there.

**Comment by hshin-g** [comment]
@garrettwong Would you be able to fix the lint errors here?

**Comment by red2k18** [comment]
@garrettwong Would you be able to fix the lint errors here?

**Pull request merged**
