### PR TITLE
CIS 3.6, 3.7 Examples

### PR DESCRIPTION
**Pull request by Red-Five**
CIS 3.6, 3.7 examples, pending confirmation we can reference CIS benchmarks in Forseti and pending Peer Review. 

Here's a handy checklist to ensure your PR goes smoothly.

- [x] I signed Google's [Contributor License Agreement](https://opensource.google.com/docs/cla/)
- [n.a. Comments] My code conforms to Google's [python style](https://google.github.io/styleguide/pyguide.html).
- [n.a. Comments] My PR at a minimum doesn't decrease unit-test coverage (if applicable).
- [n.a. Comments] My PR has been functionally tested.
- [n.a. Comments] All of the [unit-tests](https://forsetisecurity.org/docs/latest/develop/dev/testing.html) still pass.
- [n.a. Comments] Running `pylint --rcfile=pylintrc` passes.

These guidelines and more can be found in our [contributing guidelines](https://github.com/GoogleCloudPlatform/forseti-security/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dekuhn** [comment]
Just followed up internally on this we are still working through the approvals necessary to support CIS. I suspect it will be a 3 - 6 weeks until we have the necessary things in place to move forward on this.

**Comment by dekuhn** [comment]
FYI: We have announced a code freeze starting May 16, 2019, and ending May 30, 2019. During this time we won't be merging any new pull requests. For more details you can read the full announcement details [here](https://groups.google.com/a/forsetisecurity.org/forum/#!topic/announce/iIV-sr5zfds).

**Comment by dekuhn** [comment]
I expect we should be in a good place likely next week to accept these with the CIS branding.

**Comment by k5ug1** [comment]
Are all CIS benchmarks for GCP in Foreseti?

**Comment by kevensen** [comment]
@Red-Five At your convenience, could you please update this branch? I'll be happy to review this.

**Comment by kevensen** [comment]
@Red-Five At your convenience, could you please update this branch? I'll be happy to review this.

**Comment by gkowalski-google** [comment]
@Red-Five Apologies for not getting this work merged in yet, is this something you'd still like to help with?

**Comment by hshin-g** [comment]
@Red-Five would you be able to implement the changes requested above and add these rules to the Terraform rules [here](https://github.com/forseti-security/terraform-google-forseti/tree/master/modules/rules/templates/rules) as well?

Includes:
#2694 
#2698 
#2699

**Comment by Red-Five** [comment]
@hshin-g These can be merged automatically with 1 approving review.
Re the terraform copy, does github support symbolic links to avoid duplication of the files?

**Comment by Red-Five** [comment]
Added comment # These scanners have not been validated by the formal CIS certification process.

**Comment by gkowalski-google** [comment]
@Red-Five Thank you so much for sticking with these changes and getting PRs merged into the rules in the Forseti Terraform repo. Now that those have been merged in, can we close out the 4 open PRs you have for the CIS changes in the Forseti repo?

**Comment by Red-Five** [comment]
> @Red-Five Thank you so much for sticking with these changes and getting PRs merged into the rules in the Forseti Terraform repo. Now that those have been merged in, can we close out the 4 open PRs you have for the CIS changes in the Forseti repo?

Yes, the CIS pull requests are ready for review and merge once approved.

**Pull request closed without merging**
