### PR TITLE
Update get-help-bug.md

### PR DESCRIPTION
**Pull request by darrellkuhn**
Creating external PR to test website build.

### CODE REVIEW

**Comment by dekuhn** [comment]
In testing looks like travis is timing out due to no output after 10 mins calling jkyll - using verbose as a workaround is not working as it is taking more than 10 mins to run. Can use travis_wait and give it more time to run, however, even though using travis_wait is an option the command line stdout is not logged.

travis-pls is a possbile solution.
https://github.com/naftulikay/travis-pls

**Comment by blueandgold** [comment]
@darrellkuhn @dekuhn the secure build has a workaround for this.  Can we try the same thing for the unsecure build when external contributors do this?

image

**Comment by dekuhn** [comment]
@blueandgold I don't think we have an issue with secure vs unsecure with external contributor based on how the travis build is working today.

From what I have seen the build is timing out with no output to the console with Jekyll build. My last build attempt last night with travis_wait worked without any error.

Also I think this can address the long running issues with website builds timing out.

**Comment by blueandgold** [comment]
@darrellkuhn @dekuhn 

Just want to highlight this is how we force the build to stay alive, on the secure build.

image

https://github.com/forseti-security/forseti-security/blob/forsetisecurity.org-dev/travis/jekyll_build.sh#L22

**Comment by kevensen** [comment]
@darrellkuhn @dekuhn does this still need a review?  It looks like the @darrellkuhn ID hasn't signed a CLA.

**Comment by dekuhn** [comment]
@kevensen this does not need a review. I was testing the claims of external contributor not able to submit website changes based on #1913.

I have verified everything I needed with this test PR. I will close it.

**Pull request closed without merging**
