### PR TITLE
Update hyperlink mapping in manual.md

### PR DESCRIPTION
**Pull request by chemburkartushar**
Mapped hyperlink to client template instead of server template.

Thanks for opening a Pull Request!

Here's a handy checklist to ensure your PR goes smoothly.

- [x] I signed Google's [Contributor License Agreement](https://opensource.google.com/docs/cla/)
- [ ] My code conforms to Google's [python style](https://google.github.io/styleguide/pyguide.html).
- [ ] My PR at a minimum doesn't decrease unit-test coverage (if applicable).
- [ ] My PR has been functionally tested.
- [ ] All of the [tests](https://forsetisecurity.org/docs/latest/develop/dev/testing.html) pass.
- [ ] I have submitted a corresponding PR for documentation in the `forsetisecurity.org-dev branch` and included this on this PR (if applicable).
- [ ] My documentation has been functionally tested and used (if applicable).
- [ ] I have submitted a corresponding PR in the [Forseti Terraform module](https://github.com/forseti-security/terraform-google-forseti) (if applicable).

These guidelines and more can be found in our [contributing guidelines](https://github.com/forseti-security/forseti-security/blob/dev/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chemburkartushar** [comment]
@googlebot I signed it!

**Comment by gkowalski-google** [comment]
Thanks @chemburkartushar for the PR! Just FYI the same instructions are duplicated for the 2.24 and 2.25 versions of the docs:
- https://github.com/forseti-security/forseti-security/blob/forsetisecurity.org-dev/_docs/v2.24/setup/manual.md
- https://github.com/forseti-security/forseti-security/blob/forsetisecurity.org-dev/_docs/v2.25/setup/manual.md

Feel free to update those with this PR if you would like. Also, more importantly the Forseti team is not supporting the manual installation method anymore and only supports Terraform. However if you have a need for a custom deployment, then feel free to use this method. We can't offer much if, if any, support on this though.

**Comment by chemburkartushar** [comment]
Thanks @gkowalski-google for the update. I will be updating the other 2 md files as well.

**Comment by gkowalski-google** [comment]
@chemburkartushar I'll be doing a release of website changes next week, so these will go out then.

**Comment by chemburkartushar** [comment]
@gkowalski-google Sure, thanks!

**Pull request merged**
