### PR TITLE
fixes /forseti-security/forseti-security#2759

### PR DESCRIPTION
**Pull request by fawix**
This commit fixes the issue /forseti-security/forseti-security#2759 where the instance metadata was using the bucket zone and appending '-c' instead of using the actual instance zone from it's configuration.

### CODE REVIEW

**Comment by dekuhn** [comment]
FYI: We have announced a code freeze starting May 16, 2019, and ending May 30, 2019. During this time we won't be merging any new pull requests. For more details you can read the full announcement details [here](https://groups.google.com/a/forsetisecurity.org/forum/#!topic/announce/iIV-sr5zfds).

**Comment by dekuhn** [comment]
Updating branch and having CI/CD run tests again. 

Hopefully if all passes we can get this reviewed and submitted?

**Comment by fawix** [comment]
> Please remove blank line 70. This should fix the lint checking.

Done! Removed blank line 70.

**Comment by kevensen** [comment]
@fawix Is this still a work in progress?  If so, do you mind updating the branch and commenting here to let us know?

Please be advised that the Python installer will be [deprecated soon](https://forsetisecurity.org/docs/latest/setup/install-with-python-installer.html#install-with-python-installer).

**Comment by fawix** [comment]
@kevensen yes (AFAIK) - there was only one change requested in the PR (remove the blank line) which I submitted a while ago.

**Comment by kevensen** [comment]
@fawix Thank you for the clarification.  At your convenience, do you mind updating the branch?

**Comment by blueandgold** [comment]
Unfortunately, we will not be accepting this PR because we have deprecated the python installer.  But thank you for making this contribution.

**Pull request closed without merging**
