### PR TITLE
Added db user and password in the connection string.

### PR DESCRIPTION
**Pull request by joecheuk**
Resolves: #3217 , #2802
Relates: #3321 
Relates: https://github.com/forseti-security/terraform-google-forseti/pull/291

### CODE REVIEW

**Comment by kevensen** [comment]
@gkowalski-google Yeah, let's tackle that in another issue (or 2).
1. Terraform - Pass the user and password variables to the on_gke submodule.
2. Helm - Update the templates to utilize a username and password variable.

**Comment by gkowalski-google** [comment]
> @gkowalski-google Yeah, let's tackle that in another issue (or 2).
> 
> 1. Terraform - Pass the user and password variables to the on_gke submodule.
> 2. Helm - Update the templates to utilize a username and password variable.

New issue: https://github.com/forseti-security/forseti-security/issues/3294

**Comment by joecheuk** [comment]
@kevensen updated docker entry point, PTAL
@gkowalski-google I have done some investigation, using KMS here doesn't seem to provide any security benefits as if users can ssh to the VM, they can run gcloud command with the VM's elevated privilege to decrypt the password

**Comment by gkowalski-google** [comment]
> @kevensen updated docker entry point, PTAL
> @gkowalski-google I have done some investigation, using KMS here doesn't seem to provide any security benefits as if users can ssh to the VM, they can run gcloud command with the VM's elevated privilege to decrypt the password

Thanks for evaluating that!

**Comment by kevensen** [comment]
Attempt to reopen

**Pull request merged**
