### PR TITLE
[WEBSITE] Limiting the built versions for Travis build to latest and previous version

### PR DESCRIPTION
**Pull request by red2k18**
Limiting to latest and last three version docs on the website gives phenomenal results. 
Before:

image

After:

image

### CODE REVIEW

**Comment by mirons-google** [comment]
@red2k18 a quick note -- if you want to change the built versions in an on-going basis (and not a one-time basis by deleting them from the branch) you'll need to change the logic of this [script](https://github.com/forseti-security/forseti-security/blob/forsetisecurity.org/scripts/sync_latest_version.sh#L42).

**Comment by red2k18** [comment]
@mirons-google thanks, I have updated the logic of this [script](https://github.com/forseti-security/forseti-security/blob/forsetisecurity.org/scripts/sync_latest_version.sh#L42) to build latest and previous version docs, and deleted older version docs from the branch.

**Comment by red2k18** [comment]
Pruning older versions and keeping the latest and previous version brings down the time taken to build the website on Travis from 20 minutes to [7 minutes](https://travis-ci.org/forseti-security/forseti-security/builds/607679510?utm_source=github_status&utm_medium=notification). 

Check out the before and after `--profile` results of limiting built versions to latest and previous release below!

Before:

image

After:
image

**Comment by red2k18** [comment]
Opened #3519 to prune v2.15.0 - v2.22.0

**Pull request closed without merging**
