### PR TITLE
Updated resource coverage to show API/CAI data

### LINKED ISSUE #3465: Update the Resource Coverage to Show API / CAI Data
User feedback: it would be great to clarify the resource coverage by API vs CAI data.

So, in this FAQ, perhaps we can consider to add 2 columns: `CAI` and `API`.

https://forsetisecurity.org/docs/latest/faq/#resource-coverage

### PR DESCRIPTION
**Pull request by red2k18**
Resolves #3465 
This PR provides clarity on which resources Forseti is consuming from CAI vs API polling. 

Here's a handy checklist to ensure your PR goes smoothly.

- [x] I signed Google's [Contributor License Agreement](https://opensource.google.com/docs/cla/)
- [x] My code conforms to Google's [python style](https://google.github.io/styleguide/pyguide.html).
- [x] My PR has been functionally tested.
- [x] All of the [tests](https://forsetisecurity.org/docs/latest/develop/dev/testing.html) pass.

### CODE REVIEW

**Comment by hshin-g** [comment]
Thanks for submitting this @red2k18. Can you post a screenshot of what the page would look like after this change?

**Comment by red2k18** [comment]
@hshin-g Here is the screenshot

image

**Comment by hshin-g** [comment]
@red2k18 Thanks for the screenshot! Are there more resources that are being polled by GCP (e.g. GSuite) that need to be added to that second column?

**Comment by red2k18** [comment]
@hshin-g I believe there are more, but this is the only one from the list of resources documented on the website. I can research and add other resources that are not documented in that FAQ yet.

**Comment by red2k18** [comment]
@hshin-g Here is the screenshot

image

**Comment by hshin-g** [comment]
Awesome!! LGTM- thanks!

**Pull request merged**
