### PR TITLE
Additional explain tests

### PR DESCRIPTION
**Pull request by goofiva**
[root@38a20814a542 workspace]# kitchen verify --test-base-path="integration_tests/tests"
-----> Starting Kitchen (v1.24.0)
-----> Verifying <forseti-local>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-forseti-local` in directory /workspace/integration_tests/fixtures/forseti
$$$$$$ Running command `terraform output -json` in directory /workspace/integration_tests/fixtures/forseti
inventory-module: Verifying host 10.128.0.10
Skipping profile: 'inspec-gcp' on unsupported platform: 'ubuntu/18.04'.
...........................................................................................................................

Profile: forseti_integration_testing
Version: (not specified)
Target:  ssh://ubuntu@10.128.0.10:22

  ✔  explain: Command: `forseti model use 897cef3e9a1`
     ✔  Command: `forseti model use 897cef3e9a1` exit_status should eq 0
     ✔  Command: `forseti explainer access_by_authz --permission iam.serviceAccounts.get` exit_status should eq 0
     ✔  Command: `forseti explainer access_by_authz --permission iam.serviceAccounts.get` stdout should match /"resource": "project\/va-test-project-256619"/
     ✔  Command: `forseti explainer access_by_authz --permission iam.serviceAccounts.get` stdout should match /"role": "roles\/editor"/
     ✔  Command: `forseti explainer access_by_authz --role roles/storage.objectCreator` exit_status should eq 0
     ✔  Command: `forseti explainer access_by_authz --role roles/storage.objectCreator` stdout should match /va-test-project-256619/
     ✔  Command: `forseti explainer access_by_authz --role roles/storage.objectCreator` stdout should match /serviceaccount\/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com/
     ✔  Command: `forseti explainer access_by_resource organization/92932930834 | grep -c forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com` exit_status should eq 0
     ✔  Command: `forseti explainer access_by_resource organization/92932930834 | grep -c forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com` stdout should match /10/
     ✔  Command: `forseti explainer access_by_resource project/va-test-project-256619 | grep -c forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com` exit_status should eq 0
     ✔  Command: `forseti explainer access_by_resource project/va-test-project-256619 | grep -c forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com` stdout should match /5/
     ✔  Command: `forseti explainer get_policy organization/92932930834 | grep -c forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com` exit_status should eq 0
     ✔  Command: `forseti explainer get_policy organization/92932930834 | grep -c forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com` stdout should match /10/
     ✔  Command: `forseti explainer get_policy project/va-test-project-256619 | grep -c forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com` exit_status should eq 0
     ✔  Command: `forseti explainer get_policy project/va-test-project-256619 | grep -c forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com` stdout should match /5/
     ✔  Command: `forseti explainer list_members` exit_status should eq 0
     ✔  Command: `forseti explainer list_members` stdout should match /serviceaccount\/forseti\-client\-gcp\-fb135779@va\-test\-project\-256619\.iam\.gserviceaccount\.com/
     ✔  Command: `forseti explainer list_members` stdout should match /serviceaccount\/forseti\-server\-gcp\-fb135779@va\-test\-project\-256619\.iam\.gserviceaccount\.com/
     ✔  Command: `forseti explainer list_members` stdout should match /projectowner\/va\-test\-project\-256619/
     ✔  Command: `forseti explainer list_members --prefix forseti` exit_status should eq 0
     ✔  Command: `forseti explainer list_members --prefix forseti` stdout should match /serviceaccount\/forseti\-client\-gcp\-fb135779@va\-test\-project\-256619\.iam\.gserviceaccount\.com/
     ✔  Command: `forseti explainer list_members --prefix forseti` stdout should match /serviceaccount\/forseti\-server\-gcp\-fb135779@va\-test\-project\-256619\.iam\.gserviceaccount\.com/
     ✔  Command: `forseti explainer list_permissions --roles roles/iam.roleAdmin` exit_status should eq 0
     ✔  Command: `forseti explainer list_permissions --roles roles/iam.roleAdmin` stdout should match /iam.roles.create/
     ✔  Command: `forseti explainer list_permissions --roles roles/iam.roleAdmin` stdout should match /iam.roles.delete/
     ✔  Command: `forseti explainer list_permissions --roles roles/iam.roleAdmin` stdout should match /iam.roles.get/
     ✔  Command: `forseti explainer list_permissions --roles roles/iam.roleAdmin` stdout should match /iam.roles.list/
     ✔  Command: `forseti explainer list_permissions --roles roles/iam.roleAdmin` stdout should match /iam.roles.undelete/
     ✔  Command: `forseti explainer list_permissions --roles roles/iam.roleAdmin` stdout should match /iam.roles.update/
     ✔  Command: `forseti explainer list_permissions --roles roles/iam.roleAdmin` stdout should match /resourcemanager.projects.get/
     ✔  Command: `forseti explainer list_permissions --roles roles/iam.roleAdmin` stdout should match /resourcemanager.projects.getIamPolicy/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` exit_status should eq 0
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.buckets.create/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.buckets.delete/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.buckets.get/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.buckets.getIamPolicy/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.buckets.list/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.buckets.setIamPolicy/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.buckets.update/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.objects.create/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.objects.delete/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.objects.get/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.objects.getIamPolicy/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.objects.list/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.objects.setIamPolicy/
     ✔  Command: `forseti explainer list_permissions --roles roles/storage.admin` stdout should match /storage.objects.update/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` exit_status should eq 0
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.admin/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.hmacKeyAdmin/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.legacyBucketOwner/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.legacyBucketReader/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.legacyBucketWriter/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.legacyObjectOwner/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.legacyObjectReader/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.objectAdmin/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.objectCreator/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storage.objectViewer/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storagetransfer.admin/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storagetransfer.user/
     ✔  Command: `forseti explainer list_permissions --role_prefixes roles/storage` stdout should match /roles\/storagetransfer.viewer/
     ✔  Command: `forseti explainer list_roles` exit_status should eq 0
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/cloudtrace.user/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/compute.admin/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/storage.objectAdmin/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/stackdriver.accounts.viewer/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/serviceusage.serviceUsageViewer/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/servicemanagement.quotaAdmin/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/securitycenter.sourcesEditor/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/securitycenter.findingsStateSetter/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/securitycenter.findingsEditor/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/pubsub.editor/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/monitoring.viewer/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/container.clusterViewer/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/dataflow.worker/
     ✔  Command: `forseti explainer list_roles` stdout should match /roles\/datastore.viewer/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` exit_status should eq 0
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.organizationRoleAdmin/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.organizationRoleViewer/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.roleAdmin/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.roleViewer/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.securityAdmin/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.securityReviewer/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.serviceAccountAdmin/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.serviceAccountCreator/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.serviceAccountDeleter/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.serviceAccountKeyAdmin/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.serviceAccountTokenCreator/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.serviceAccountUser/
     ✔  Command: `forseti explainer list_roles --prefix roles/iam` stdout should match /roles\/iam.workloadIdentityUser/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` exit_status should eq 0
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.admin/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.hmacKeyAdmin/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.legacyBucketOwner/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.legacyBucketReader/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.legacyBucketWriter/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.legacyObjectOwner/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.legacyObjectReader/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.objectAdmin/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.objectCreator/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storage.objectViewer/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storagetransfer.admin/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storagetransfer.user/
     ✔  Command: `forseti explainer list_roles --prefix roles/storage` stdout should match /roles\/storagetransfer.viewer/
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --role roles/resourcemanager.organizationAdmin` exit_status should eq 0
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --role roles/resourcemanager.organizationAdmin` stdout should match "forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com"
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --role roles/resourcemanager.organizationAdmin` stdout should match "forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com"
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --role roles/resourcemanager.organizationAdmin` stdout should match /organization\/92932930834/
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --role roles/resourcemanager.organizationAdmin` stdout should match /roles\/resourcemanager.organizationAdmin/
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --role roles/resourcemanager.organizationAdmin` stdout should match /"overgranting": 0/
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com project/va-test-project-256619 --permission storage.buckets.delete` exit_status should eq 0
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com project/va-test-project-256619 --permission storage.buckets.delete` stdout should match /roles\/cloudmigration.inframanager/
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com project/va-test-project-256619 --permission storage.buckets.delete` stdout should match /roles\/owner/
     ✔  Command: `forseti explainer why_denied serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com project/va-test-project-256619 --permission storage.buckets.delete` stdout should match /roles\/storage.admin/
     ✔  Command: `forseti explainer why_granted serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --permission iam.serviceAccounts.get` exit_status should eq 0
     ✔  Command: `forseti explainer why_granted serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --permission iam.serviceAccounts.get` stdout should match /roles\/iam.securityReviewer/
     ✔  Command: `forseti explainer why_granted serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com project/va-test-project-256619 --permission compute.instances.get` exit_status should eq 0
     ✔  Command: `forseti explainer why_granted serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com project/va-test-project-256619 --permission compute.instances.get` stdout should match /roles\/compute.networkViewer/
     ✔  Command: `forseti explainer why_granted serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --role roles/iam.securityReviewer` exit_status should eq 0
     ✔  Command: `forseti explainer why_granted serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com organization/92932930834 --role roles/iam.securityReviewer` stdout should match /organization\/92932930834/
     ✔  Command: `forseti explainer why_granted serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com project/va-test-project-256619 --role roles/compute.networkViewer` exit_status should eq 0
     ✔  Command: `forseti explainer why_granted serviceaccount/forseti-server-gcp-fb135779@va-test-project-256619.iam.gserviceaccount.com project/va-test-project-256619 --role roles/compute.networkViewer` stdout should match /organization\/92932930834/
     ✔  Command: `forseti inventory delete 1574336313944098` exit_status should eq 0
     ✔  Command: `forseti model delete 897cef3e9a1` exit_status should eq 0

Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 123 successful, 0 failures, 0 skipped
       Finished verifying <forseti-local> (1m13.21s).
-----> Kitchen is finished. (1m15.30s)

### CODE REVIEW

**Comment by gkowalski-google** [comment]
Looks good, will try this locally. Can you add a comment about which issues this resolves?

**Comment by goofiva** [comment]
This PR resolves...

https://github.com/forseti-security/forseti-security/issues/3474
https://github.com/forseti-security/forseti-security/issues/3473
https://github.com/forseti-security/forseti-security/issues/3472
https://github.com/forseti-security/forseti-security/issues/3471
https://github.com/forseti-security/forseti-security/issues/3470

**Comment by gkowalski-google** [comment]
> This PR resolves...
> 
> #3474
> #3473
> #3472
> #3471
> #3470

Everything looks good, but I do not see the tests for #3472. It can be done in a different PR. For that ticket, is it possible to verify the output matches this as a single string? By doing so we asserting that member has the roles/browser role on the org. There can be multiple members listed.
```
"resources": [ "organization/92932930834" ], "role": "roles/browser"
```

**Comment by goofiva** [comment]
> > This PR resolves...
> > #3474
> > #3473
> > #3472
> > #3471
> > #3470
> 
> Everything looks good, but I do not see the tests for #3472. It can be done in a different PR. For that ticket, is it possible to verify the output matches this as a single string? By doing so we asserting that member has the roles/browser role on the org. There can be multiple members listed.
> 
> ```
> "resources": [ "organization/92932930834" ], "role": "roles/browser"
> ```



> > This PR resolves...
> > #3474
> > #3473
> > #3472
> > #3471
> > #3470
> 
> Everything looks good, but I do not see the tests for #3472. It can be done in a different PR. For that ticket, is it possible to verify the output matches this as a single string? By doing so we asserting that member has the roles/browser role on the org. There can be multiple members listed.
> 
> ```
> "resources": [ "organization/92932930834" ], "role": "roles/browser"
> ```

https://github.com/forseti-security/forseti-security/pull/3476/files#diff-f81ac774379e13bd7da43243de385ffcR32-R45

Added the tests here.

**Pull request merged**
